---
minio:
  address: localhost
  port: 9000
  accesskey: MySecretAccessKey
  secretkey: MySecretSecretKeyforMinio
  ssl: false
gleaner:
  runid: dec28 # this will be the bucket the output is placed in...
  summon: true # do we want to visit the web sites and pull down the files
  mill: true
  tmpdir: ""
context:
  cache: true
contextmaps:
- prefix: "https://schema.org/"
  file: "/home/fils/Project418/gleaner/docs/jsonldcontext.json"
- prefix: "http://schema.org/"
  file: "/home/fils/Project418/gleaner/docs/jsonldcontext.json"
- prefix: "https://schema.org"
  file: "/home/fils/Project418/gleaner/docs/jsonldcontext.json"
- prefix: "http://schema.org"
  file: "/home/fils/Project418/gleaner/docs/jsonldcontext.json"
summoner:
  mode: diff  # [time, hash, none] diff: look for difference or full: delete old objects and replace
millers:
  graph: true
  shacl: false
  prov: false
shapefiles:
- ref: https://raw.githubusercontent.com/geoschemas-org/geoshapes/master/shapegraphs/googleRequired.ttl
- ref: https://raw.githubusercontent.com/geoschemas-org/geoshapes/master/shapegraphs/googleRecommendedCoverageCheck.ttl
sources:
- name: opencore
  logo: http://geodex.org/images/logos/EarthCubeLogo.png
  url: http://opencoredata.org/sitemap.xml
  headless: false
# - name: baltoopendaporg
#   logo: http://geodex.org/images/logos/EarthCubeLogo.png
#   url: http://balto.opendap.org/opendap/site_map.txt   # XML version available?
#   headless: false
- name: ssdbiodporg
  logo: https://ssdb.iodp.org/images/head_logo_PRO.gif
  url: https://ssdb.iodp.org/dataset/sitemap.xml
  headless: false
- name: wwwhydroshareorg
  logo: http://geodex.org/images/logos/cuahsiHydroshare.png
  url: https://www.hydroshare.org/sitemap-resources.xml
  headless: false
- name: dataneotomadborg
  logo: http://geodex.org/images/logos/neotoma.png
  url: http://data.neotomadb.org/sitemap.xml
  headless: false
- name: earthreforg
  logo: http://geodex.org/images/logos/magic.png
  url: https://www2.earthref.org/MagIC/contributions.sitemap.xml
  headless: true
- name: getiedadataorg
  logo: http://geodex.org/images/logos/ieda_maplogo.png
  url: http://get.iedadata.org/doi/xml-sitemap.php
  headless: false
- name: opentopographyorg
  logo: http://geodex.org/images/logos/opentopo.png
  url: https://opentopography.org/sitemap.xml
  headless: false
- name: wikilinkedearth
  logo: http://geodex.org/images/logos/linkedEarth.jpeg
  url: http://wiki.linked.earth/sitemap.xml
  headless: false
- name: wwwbco-dmoorg
  logo: http://geodex.org/images/logos/bco-dmo-words-BLUE.jpg
  url: https://www.bco-dmo.org/sitemap.xml
  headless: false
- name: wwwunavcoorg
  logo: http://geodex.org/images/logos/uv-logo.png
  url: https://www.unavco.org/data/doi/sitemap.xml
  headless: false
- name: dsirisedu
  logo: http://geodex.org/images/logos/iris_color_screen_lrg.png
  url: http://ds.iris.edu/files/sitemap.xml
  headless: false
- name: portaledirepositoryorg
  logo: https://portal.edirepository.org/nis/images/EDI-logo-300DPI_5.png
  url: https://portal.edirepository.org/sitemap_index.xml
  headless: false
- name: datadiscoverystudioorg
  logo: http://geodex.org/images/logos/EarthCubeLogo.png
  url: http://datadiscoverystudio.org/sitemap/CinergiSiteIndex.xml 
  headless: false
- name: dataucaredu 
  logo: http://geodex.org/images/logos/EarthCubeLogo.png
  url:  https://data.ucar.edu/sitemap.xml 
  headless: false
