---
gleaner:
  summon: true # do we want to visit the web sites and pull down the files
  mill: true
  runid: unidataT2  # this will be the bucket the output is placed in...
summoner:
  mode: diff  # one of diff: look for difference or full: delete old objects and replace
millers:
  mock: false
  graph: true
  spatial: false
  shacl: true
  organic: false
  tika: false
  fdptika: false
  fdptikajena: false
  fdpgraph: false
  prov: false
sources:
- name: thredds-testunidataucaredu
  shortname: unidata
  logo: http://geodex.org/images/logos/EarthCubeLogo.png
  url: https://thredds-test.unidata.ucar.edu/geocodesmap.xml
  headless: false
  sitemapformat: xml
  active: true
